###
GET  http://localhost:4000/api/users/

###
GET  http://localhost:4000/api/users/608719427268bc18e47ddff2

###
POST http://localhost:4000/api/users/
Content-Type: application/json

{ 
    "name": "Aasdasd",
    "username": "Ark88",
    "email": "pedroafigueredo@gmaill.com",
    "address": "San Juan de Dios 658",
    "phone": "53120354",
    "website": "www.ark88.com",
    "company": "Freelancers"
}


###
DELETE http://localhost:4000/api/users/60833495af12d32410bc74eb


###
PUT http://localhost:4000/api/users/608719427268bc18e47ddff2
Content-Type: application/json

{ 
    "name": "llllllll",
    "username": "Ark88",
    "email": "pedroafigueredo@gmaill.com",
    "address": "asdasd",
    "phone": "asdasd",
    "website": "asdasd",
    "company": "sss"
}
